import os

#ENV VARIABLES
DB_CONNECTION_URI = os.getenv('DB_CONNECTION_URI','')
DB_CONNECTION_API_CREDENTIALS = os.getenv('DB_CONNECTION_API_CREDENTIALS','') #applicable only for bigquery connection
DB_CONNECTION_DB = 'datastore'
TWITTER_API_KEY=os.getenv('TWITTER_API_KEY','')
TWITTER_API_KEY_SECRET=os.getenv('TWITTER_API_KEY_SECRET','')
TWITTER_ACCESS_TOKEN=os.getenv('TWITTER_ACCESS_TOKEN','')
TWITTER_ACCESS_TOKEN_SECRET=os.getenv('TWITTER_ACCESS_TOKEN_SECRET','')